name: concurrent pr labels
on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize
    
jobs:
  comment:
    if: |
      ( github.event.action == 'labeled' && github.event.label.name == 'comments') ||
      ( github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'comments') )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello from a non-limited ${{ github.event_name }} ${{ github.event.action }} event